---
- hosts: all
  become: true
  tasks:
  - name : Install git
    package:
     name: git
     state: present
    
  - name: Run update
    apt:
     update_cache: true
     
  - name: Install jdk
    package:
     name: default-jdk
     state: present
  
  - name: Copy chromedriver
    copy:
     src: /home/user/chromedirver
     dest: /home/user
    
  - name: Install chromium browser
    package:
     name: chromium-browser
     state: present
     
  - name: Install chromium driver
    package:
     name: chromium-chromedriver
     state: present
     
  - name: Copy agents.jar file
    copy:
     src: /home/user/Downloads/agent.jar
     dest: /home/user
     
  - name: Run update
    apt:
     update_cache: yes
     
    
